name: zinc
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d9e7e8'
    - '#b77fa2'
    - '#25242a'
    - '#459886'
    - '#2b675b'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
